<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-04T16:57:22 EET" name="Default suite" finished-at="2025-03-04T16:57:25 EET" duration-ms="2641">
    <groups>
    </groups>
    <test started-at="2025-03-04T16:57:22 EET" name="Default test" finished-at="2025-03-04T16:57:25 EET" duration-ms="2641">
      <class name="restassured.TCs">
        <test-method is-config="true" signature="setup()[pri:0, instance:restassured.TCs@3a52dba3]" started-at="2025-03-04T16:57:22 EET" name="setup" finished-at="2025-03-04T16:57:22 EET" duration-ms="262" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="createUserType()[pri:1, instance:restassured.TCs@3a52dba3]" started-at="2025-03-04T16:57:22 EET" name="createUserType" finished-at="2025-03-04T16:57:24 EET" duration-ms="1675" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUserType -->
        <test-method signature="errorHandlingUserwithEmptyData()[pri:2, instance:restassured.TCs@3a52dba3]" started-at="2025-03-04T16:57:24 EET" name="errorHandlingUserwithEmptyData" finished-at="2025-03-04T16:57:24 EET" duration-ms="246" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Required Parameters cannot be empty expected [400] but found [201]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Required Parameters cannot be empty expected [400] but found [201]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at restassured.TCs.errorHandlingUserwithEmptyData(TCs.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorHandlingUserwithEmptyData -->
        <test-method signature="getUserData()[pri:3, instance:restassured.TCs@3a52dba3]" started-at="2025-03-04T16:57:24 EET" name="getUserData" finished-at="2025-03-04T16:57:24 EET" duration-ms="207" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserData -->
        <test-method signature="errorhandlingNonExistingUser()[pri:4, instance:restassured.TCs@3a52dba3]" started-at="2025-03-04T16:57:24 EET" name="errorhandlingNonExistingUser" finished-at="2025-03-04T16:57:24 EET" duration-ms="233" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorhandlingNonExistingUser -->
        <test-method signature="updateUserTest()[pri:5, instance:restassured.TCs@3a52dba3]" started-at="2025-03-04T16:57:24 EET" name="updateUserTest" finished-at="2025-03-04T16:57:25 EET" duration-ms="247" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateUserTest -->
      </class> <!-- restassured.TCs -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
